sudo: required

branches:
  only:
    - master

language: c++

compiler:
  - gcc
  - clang

notifications:
  email: false

arch:
  packages:
    - cmake
    - python-pip
    - strace
    - flake8
    - clang
    - gcc
    - sdl2
    - tinyxml
    - tinyxml2
    - sfml
    - bullet
    - boost
    - google-glog
    - gtest
    - eigen3
    - nlohmann-json
  script:
    - sudo chmod 777 -R /dev/shm/
    - ./scripts/run_tests.sh $CC $CXX -j4

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
