language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX_COMPILER=g++-6
        - COMPILER=gcc-6
        - TEST_CHECK=NO

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX_COMPILER=g++-7
        - COMPILER=gcc-7
        - TEST_CHECK=NO

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'g++-6']
      env:
        - CXX_COMPILER=clang++-3.9
        - COMPILER=clang-3.9
        - TEST_CHECK=NO

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0', 'g++-6']
      env:
        - CXX_COMPILER=clang++-4.0
        - COMPILER=clang-4.0

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - CXX_COMPILER=clang++
        - COMPILER=clang

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - CXX_COMPILER=clang++
        - COMPILER=clang

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - CXX_COMPILER=clang++
        - COMPILER=clang

    - os: osx
      osx_image: xcode9
      compiler: clang
      env:
        - CXX_COMPILER=clang++
        - COMPILER=clang


addons:
  apt:
    packages:
      - tree

script:
  - mkdir build
  - cd build
  - ../run_tests.sh $COMPILER $CXX_COMPILER $TEST_CHECK
