sudo: required

branches:
  only:
    - master

language: c++

compiler:
  - clang

notifications:
  email: false

env:
  - MODULES=On CXX_COMPILER=clang++ COMPILER=clang
  - MODULES=Off CXX_COMPILER=clang++ COMPILER=clang

arch:
  packages:
    - cmake
    - clang
    - clang-tools-extra
    - llvm-libs
    - llvm
    - python
    - python3
  script:
    - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
